// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package curriculum

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_CourseEquivalence                   protoreflect.MessageDescriptor
	fd_CourseEquivalence_index             protoreflect.FieldDescriptor
	fd_CourseEquivalence_sourceTokenId     protoreflect.FieldDescriptor
	fd_CourseEquivalence_targetInstitution protoreflect.FieldDescriptor
	fd_CourseEquivalence_targetCourseCode  protoreflect.FieldDescriptor
	fd_CourseEquivalence_equivalenceStatus protoreflect.FieldDescriptor
	fd_CourseEquivalence_approvalCount     protoreflect.FieldDescriptor
)

func init() {
	file_academictoken_curriculum_course_equivalence_proto_init()
	md_CourseEquivalence = File_academictoken_curriculum_course_equivalence_proto.Messages().ByName("CourseEquivalence")
	fd_CourseEquivalence_index = md_CourseEquivalence.Fields().ByName("index")
	fd_CourseEquivalence_sourceTokenId = md_CourseEquivalence.Fields().ByName("sourceTokenId")
	fd_CourseEquivalence_targetInstitution = md_CourseEquivalence.Fields().ByName("targetInstitution")
	fd_CourseEquivalence_targetCourseCode = md_CourseEquivalence.Fields().ByName("targetCourseCode")
	fd_CourseEquivalence_equivalenceStatus = md_CourseEquivalence.Fields().ByName("equivalenceStatus")
	fd_CourseEquivalence_approvalCount = md_CourseEquivalence.Fields().ByName("approvalCount")
}

var _ protoreflect.Message = (*fastReflection_CourseEquivalence)(nil)

type fastReflection_CourseEquivalence CourseEquivalence

func (x *CourseEquivalence) ProtoReflect() protoreflect.Message {
	return (*fastReflection_CourseEquivalence)(x)
}

func (x *CourseEquivalence) slowProtoReflect() protoreflect.Message {
	mi := &file_academictoken_curriculum_course_equivalence_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_CourseEquivalence_messageType fastReflection_CourseEquivalence_messageType
var _ protoreflect.MessageType = fastReflection_CourseEquivalence_messageType{}

type fastReflection_CourseEquivalence_messageType struct{}

func (x fastReflection_CourseEquivalence_messageType) Zero() protoreflect.Message {
	return (*fastReflection_CourseEquivalence)(nil)
}
func (x fastReflection_CourseEquivalence_messageType) New() protoreflect.Message {
	return new(fastReflection_CourseEquivalence)
}
func (x fastReflection_CourseEquivalence_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_CourseEquivalence
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_CourseEquivalence) Descriptor() protoreflect.MessageDescriptor {
	return md_CourseEquivalence
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_CourseEquivalence) Type() protoreflect.MessageType {
	return _fastReflection_CourseEquivalence_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_CourseEquivalence) New() protoreflect.Message {
	return new(fastReflection_CourseEquivalence)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_CourseEquivalence) Interface() protoreflect.ProtoMessage {
	return (*CourseEquivalence)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_CourseEquivalence) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_CourseEquivalence_index, value) {
			return
		}
	}
	if x.SourceTokenId != "" {
		value := protoreflect.ValueOfString(x.SourceTokenId)
		if !f(fd_CourseEquivalence_sourceTokenId, value) {
			return
		}
	}
	if x.TargetInstitution != "" {
		value := protoreflect.ValueOfString(x.TargetInstitution)
		if !f(fd_CourseEquivalence_targetInstitution, value) {
			return
		}
	}
	if x.TargetCourseCode != "" {
		value := protoreflect.ValueOfString(x.TargetCourseCode)
		if !f(fd_CourseEquivalence_targetCourseCode, value) {
			return
		}
	}
	if x.EquivalenceStatus != uint64(0) {
		value := protoreflect.ValueOfUint64(x.EquivalenceStatus)
		if !f(fd_CourseEquivalence_equivalenceStatus, value) {
			return
		}
	}
	if x.ApprovalCount != uint64(0) {
		value := protoreflect.ValueOfUint64(x.ApprovalCount)
		if !f(fd_CourseEquivalence_approvalCount, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_CourseEquivalence) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "academictoken.curriculum.CourseEquivalence.index":
		return x.Index != ""
	case "academictoken.curriculum.CourseEquivalence.sourceTokenId":
		return x.SourceTokenId != ""
	case "academictoken.curriculum.CourseEquivalence.targetInstitution":
		return x.TargetInstitution != ""
	case "academictoken.curriculum.CourseEquivalence.targetCourseCode":
		return x.TargetCourseCode != ""
	case "academictoken.curriculum.CourseEquivalence.equivalenceStatus":
		return x.EquivalenceStatus != uint64(0)
	case "academictoken.curriculum.CourseEquivalence.approvalCount":
		return x.ApprovalCount != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.curriculum.CourseEquivalence"))
		}
		panic(fmt.Errorf("message academictoken.curriculum.CourseEquivalence does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CourseEquivalence) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "academictoken.curriculum.CourseEquivalence.index":
		x.Index = ""
	case "academictoken.curriculum.CourseEquivalence.sourceTokenId":
		x.SourceTokenId = ""
	case "academictoken.curriculum.CourseEquivalence.targetInstitution":
		x.TargetInstitution = ""
	case "academictoken.curriculum.CourseEquivalence.targetCourseCode":
		x.TargetCourseCode = ""
	case "academictoken.curriculum.CourseEquivalence.equivalenceStatus":
		x.EquivalenceStatus = uint64(0)
	case "academictoken.curriculum.CourseEquivalence.approvalCount":
		x.ApprovalCount = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.curriculum.CourseEquivalence"))
		}
		panic(fmt.Errorf("message academictoken.curriculum.CourseEquivalence does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_CourseEquivalence) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "academictoken.curriculum.CourseEquivalence.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "academictoken.curriculum.CourseEquivalence.sourceTokenId":
		value := x.SourceTokenId
		return protoreflect.ValueOfString(value)
	case "academictoken.curriculum.CourseEquivalence.targetInstitution":
		value := x.TargetInstitution
		return protoreflect.ValueOfString(value)
	case "academictoken.curriculum.CourseEquivalence.targetCourseCode":
		value := x.TargetCourseCode
		return protoreflect.ValueOfString(value)
	case "academictoken.curriculum.CourseEquivalence.equivalenceStatus":
		value := x.EquivalenceStatus
		return protoreflect.ValueOfUint64(value)
	case "academictoken.curriculum.CourseEquivalence.approvalCount":
		value := x.ApprovalCount
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.curriculum.CourseEquivalence"))
		}
		panic(fmt.Errorf("message academictoken.curriculum.CourseEquivalence does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CourseEquivalence) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "academictoken.curriculum.CourseEquivalence.index":
		x.Index = value.Interface().(string)
	case "academictoken.curriculum.CourseEquivalence.sourceTokenId":
		x.SourceTokenId = value.Interface().(string)
	case "academictoken.curriculum.CourseEquivalence.targetInstitution":
		x.TargetInstitution = value.Interface().(string)
	case "academictoken.curriculum.CourseEquivalence.targetCourseCode":
		x.TargetCourseCode = value.Interface().(string)
	case "academictoken.curriculum.CourseEquivalence.equivalenceStatus":
		x.EquivalenceStatus = value.Uint()
	case "academictoken.curriculum.CourseEquivalence.approvalCount":
		x.ApprovalCount = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.curriculum.CourseEquivalence"))
		}
		panic(fmt.Errorf("message academictoken.curriculum.CourseEquivalence does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CourseEquivalence) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "academictoken.curriculum.CourseEquivalence.index":
		panic(fmt.Errorf("field index of message academictoken.curriculum.CourseEquivalence is not mutable"))
	case "academictoken.curriculum.CourseEquivalence.sourceTokenId":
		panic(fmt.Errorf("field sourceTokenId of message academictoken.curriculum.CourseEquivalence is not mutable"))
	case "academictoken.curriculum.CourseEquivalence.targetInstitution":
		panic(fmt.Errorf("field targetInstitution of message academictoken.curriculum.CourseEquivalence is not mutable"))
	case "academictoken.curriculum.CourseEquivalence.targetCourseCode":
		panic(fmt.Errorf("field targetCourseCode of message academictoken.curriculum.CourseEquivalence is not mutable"))
	case "academictoken.curriculum.CourseEquivalence.equivalenceStatus":
		panic(fmt.Errorf("field equivalenceStatus of message academictoken.curriculum.CourseEquivalence is not mutable"))
	case "academictoken.curriculum.CourseEquivalence.approvalCount":
		panic(fmt.Errorf("field approvalCount of message academictoken.curriculum.CourseEquivalence is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.curriculum.CourseEquivalence"))
		}
		panic(fmt.Errorf("message academictoken.curriculum.CourseEquivalence does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_CourseEquivalence) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "academictoken.curriculum.CourseEquivalence.index":
		return protoreflect.ValueOfString("")
	case "academictoken.curriculum.CourseEquivalence.sourceTokenId":
		return protoreflect.ValueOfString("")
	case "academictoken.curriculum.CourseEquivalence.targetInstitution":
		return protoreflect.ValueOfString("")
	case "academictoken.curriculum.CourseEquivalence.targetCourseCode":
		return protoreflect.ValueOfString("")
	case "academictoken.curriculum.CourseEquivalence.equivalenceStatus":
		return protoreflect.ValueOfUint64(uint64(0))
	case "academictoken.curriculum.CourseEquivalence.approvalCount":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.curriculum.CourseEquivalence"))
		}
		panic(fmt.Errorf("message academictoken.curriculum.CourseEquivalence does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_CourseEquivalence) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in academictoken.curriculum.CourseEquivalence", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_CourseEquivalence) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CourseEquivalence) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_CourseEquivalence) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_CourseEquivalence) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*CourseEquivalence)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SourceTokenId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.TargetInstitution)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.TargetCourseCode)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.EquivalenceStatus != 0 {
			n += 1 + runtime.Sov(uint64(x.EquivalenceStatus))
		}
		if x.ApprovalCount != 0 {
			n += 1 + runtime.Sov(uint64(x.ApprovalCount))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*CourseEquivalence)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.ApprovalCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ApprovalCount))
			i--
			dAtA[i] = 0x30
		}
		if x.EquivalenceStatus != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.EquivalenceStatus))
			i--
			dAtA[i] = 0x28
		}
		if len(x.TargetCourseCode) > 0 {
			i -= len(x.TargetCourseCode)
			copy(dAtA[i:], x.TargetCourseCode)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TargetCourseCode)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.TargetInstitution) > 0 {
			i -= len(x.TargetInstitution)
			copy(dAtA[i:], x.TargetInstitution)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TargetInstitution)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.SourceTokenId) > 0 {
			i -= len(x.SourceTokenId)
			copy(dAtA[i:], x.SourceTokenId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SourceTokenId)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*CourseEquivalence)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: CourseEquivalence: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: CourseEquivalence: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SourceTokenId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SourceTokenId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TargetInstitution", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TargetInstitution = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TargetCourseCode", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TargetCourseCode = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EquivalenceStatus", wireType)
				}
				x.EquivalenceStatus = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.EquivalenceStatus |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ApprovalCount", wireType)
				}
				x.ApprovalCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ApprovalCount |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: academictoken/curriculum/course_equivalence.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseEquivalence struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index             string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	SourceTokenId     string `protobuf:"bytes,2,opt,name=sourceTokenId,proto3" json:"sourceTokenId,omitempty"`
	TargetInstitution string `protobuf:"bytes,3,opt,name=targetInstitution,proto3" json:"targetInstitution,omitempty"`
	TargetCourseCode  string `protobuf:"bytes,4,opt,name=targetCourseCode,proto3" json:"targetCourseCode,omitempty"`
	EquivalenceStatus uint64 `protobuf:"varint,5,opt,name=equivalenceStatus,proto3" json:"equivalenceStatus,omitempty"`
	ApprovalCount     uint64 `protobuf:"varint,6,opt,name=approvalCount,proto3" json:"approvalCount,omitempty"`
}

func (x *CourseEquivalence) Reset() {
	*x = CourseEquivalence{}
	if protoimpl.UnsafeEnabled {
		mi := &file_academictoken_curriculum_course_equivalence_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseEquivalence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseEquivalence) ProtoMessage() {}

// Deprecated: Use CourseEquivalence.ProtoReflect.Descriptor instead.
func (*CourseEquivalence) Descriptor() ([]byte, []int) {
	return file_academictoken_curriculum_course_equivalence_proto_rawDescGZIP(), []int{0}
}

func (x *CourseEquivalence) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *CourseEquivalence) GetSourceTokenId() string {
	if x != nil {
		return x.SourceTokenId
	}
	return ""
}

func (x *CourseEquivalence) GetTargetInstitution() string {
	if x != nil {
		return x.TargetInstitution
	}
	return ""
}

func (x *CourseEquivalence) GetTargetCourseCode() string {
	if x != nil {
		return x.TargetCourseCode
	}
	return ""
}

func (x *CourseEquivalence) GetEquivalenceStatus() uint64 {
	if x != nil {
		return x.EquivalenceStatus
	}
	return 0
}

func (x *CourseEquivalence) GetApprovalCount() uint64 {
	if x != nil {
		return x.ApprovalCount
	}
	return 0
}

var File_academictoken_curriculum_course_equivalence_proto protoreflect.FileDescriptor

var file_academictoken_curriculum_course_equivalence_proto_rawDesc = []byte{
	0x0a, 0x31, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f,
	0x63, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x75, 0x6d, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x5f, 0x65, 0x71, 0x75, 0x69, 0x76, 0x61, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x18, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x2e, 0x63, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x75, 0x6d, 0x22, 0xfd, 0x01,
	0x0a, 0x11, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x45, 0x71, 0x75, 0x69, 0x76, 0x61, 0x6c, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x11, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x69, 0x74, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a,
	0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x43,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x65, 0x71, 0x75,
	0x69, 0x76, 0x61, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x65, 0x71, 0x75, 0x69, 0x76, 0x61, 0x6c, 0x65, 0x6e, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d,
	0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0xfb, 0x01,
	0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x2e, 0x63, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x75, 0x6d, 0x42, 0x16,
	0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x45, 0x71, 0x75, 0x69, 0x76, 0x61, 0x6c, 0x65, 0x6e, 0x63,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x69, 0x61, 0x6e, 0x63, 0x61, 0x2d, 0x32, 0x39, 0x4d, 0x53,
	0x50, 0x2f, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x75, 0x6d, 0xa2, 0x02, 0x03, 0x41,
	0x43, 0x58, 0xaa, 0x02, 0x18, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x75, 0x6d, 0xca, 0x02, 0x18,
	0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5c, 0x43, 0x75,
	0x72, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x75, 0x6d, 0xe2, 0x02, 0x24, 0x41, 0x63, 0x61, 0x64, 0x65,
	0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5c, 0x43, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75,
	0x6c, 0x75, 0x6d, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x19, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3a,
	0x3a, 0x43, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_academictoken_curriculum_course_equivalence_proto_rawDescOnce sync.Once
	file_academictoken_curriculum_course_equivalence_proto_rawDescData = file_academictoken_curriculum_course_equivalence_proto_rawDesc
)

func file_academictoken_curriculum_course_equivalence_proto_rawDescGZIP() []byte {
	file_academictoken_curriculum_course_equivalence_proto_rawDescOnce.Do(func() {
		file_academictoken_curriculum_course_equivalence_proto_rawDescData = protoimpl.X.CompressGZIP(file_academictoken_curriculum_course_equivalence_proto_rawDescData)
	})
	return file_academictoken_curriculum_course_equivalence_proto_rawDescData
}

var file_academictoken_curriculum_course_equivalence_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_academictoken_curriculum_course_equivalence_proto_goTypes = []interface{}{
	(*CourseEquivalence)(nil), // 0: academictoken.curriculum.CourseEquivalence
}
var file_academictoken_curriculum_course_equivalence_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_academictoken_curriculum_course_equivalence_proto_init() }
func file_academictoken_curriculum_course_equivalence_proto_init() {
	if File_academictoken_curriculum_course_equivalence_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_academictoken_curriculum_course_equivalence_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseEquivalence); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_academictoken_curriculum_course_equivalence_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_academictoken_curriculum_course_equivalence_proto_goTypes,
		DependencyIndexes: file_academictoken_curriculum_course_equivalence_proto_depIdxs,
		MessageInfos:      file_academictoken_curriculum_course_equivalence_proto_msgTypes,
	}.Build()
	File_academictoken_curriculum_course_equivalence_proto = out.File
	file_academictoken_curriculum_course_equivalence_proto_rawDesc = nil
	file_academictoken_curriculum_course_equivalence_proto_goTypes = nil
	file_academictoken_curriculum_course_equivalence_proto_depIdxs = nil
}
