// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package curriculum

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var _ protoreflect.List = (*_CourseContent_9_list)(nil)

type _CourseContent_9_list struct {
	list *[]string
}

func (x *_CourseContent_9_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_CourseContent_9_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_CourseContent_9_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_CourseContent_9_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_CourseContent_9_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message CourseContent at list field Objectives as it is not of Message kind"))
}

func (x *_CourseContent_9_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_CourseContent_9_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_CourseContent_9_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_CourseContent_10_list)(nil)

type _CourseContent_10_list struct {
	list *[]string
}

func (x *_CourseContent_10_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_CourseContent_10_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_CourseContent_10_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_CourseContent_10_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_CourseContent_10_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message CourseContent at list field TopicUnits as it is not of Message kind"))
}

func (x *_CourseContent_10_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_CourseContent_10_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_CourseContent_10_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_CourseContent_11_list)(nil)

type _CourseContent_11_list struct {
	list *[]string
}

func (x *_CourseContent_11_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_CourseContent_11_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_CourseContent_11_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_CourseContent_11_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_CourseContent_11_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message CourseContent at list field Methodologies as it is not of Message kind"))
}

func (x *_CourseContent_11_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_CourseContent_11_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_CourseContent_11_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_CourseContent_12_list)(nil)

type _CourseContent_12_list struct {
	list *[]string
}

func (x *_CourseContent_12_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_CourseContent_12_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_CourseContent_12_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_CourseContent_12_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_CourseContent_12_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message CourseContent at list field EvaluationMethods as it is not of Message kind"))
}

func (x *_CourseContent_12_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_CourseContent_12_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_CourseContent_12_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_CourseContent_13_list)(nil)

type _CourseContent_13_list struct {
	list *[]string
}

func (x *_CourseContent_13_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_CourseContent_13_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_CourseContent_13_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_CourseContent_13_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_CourseContent_13_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message CourseContent at list field BibliographyBasic as it is not of Message kind"))
}

func (x *_CourseContent_13_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_CourseContent_13_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_CourseContent_13_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_CourseContent_14_list)(nil)

type _CourseContent_14_list struct {
	list *[]string
}

func (x *_CourseContent_14_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_CourseContent_14_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_CourseContent_14_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_CourseContent_14_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_CourseContent_14_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message CourseContent at list field BibliographyComplementary as it is not of Message kind"))
}

func (x *_CourseContent_14_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_CourseContent_14_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_CourseContent_14_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_CourseContent_15_list)(nil)

type _CourseContent_15_list struct {
	list *[]string
}

func (x *_CourseContent_15_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_CourseContent_15_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_CourseContent_15_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_CourseContent_15_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_CourseContent_15_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message CourseContent at list field Keywords as it is not of Message kind"))
}

func (x *_CourseContent_15_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_CourseContent_15_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_CourseContent_15_list) IsValid() bool {
	return x.list != nil
}

var (
	md_CourseContent                           protoreflect.MessageDescriptor
	fd_CourseContent_index                     protoreflect.FieldDescriptor
	fd_CourseContent_courseId                  protoreflect.FieldDescriptor
	fd_CourseContent_institution               protoreflect.FieldDescriptor
	fd_CourseContent_title                     protoreflect.FieldDescriptor
	fd_CourseContent_code                      protoreflect.FieldDescriptor
	fd_CourseContent_workloadHours             protoreflect.FieldDescriptor
	fd_CourseContent_credits                   protoreflect.FieldDescriptor
	fd_CourseContent_description               protoreflect.FieldDescriptor
	fd_CourseContent_objectives                protoreflect.FieldDescriptor
	fd_CourseContent_topicUnits                protoreflect.FieldDescriptor
	fd_CourseContent_methodologies             protoreflect.FieldDescriptor
	fd_CourseContent_evaluationMethods         protoreflect.FieldDescriptor
	fd_CourseContent_bibliographyBasic         protoreflect.FieldDescriptor
	fd_CourseContent_bibliographyComplementary protoreflect.FieldDescriptor
	fd_CourseContent_keywords                  protoreflect.FieldDescriptor
	fd_CourseContent_contentHash               protoreflect.FieldDescriptor
)

func init() {
	file_academictoken_curriculum_course_content_proto_init()
	md_CourseContent = File_academictoken_curriculum_course_content_proto.Messages().ByName("CourseContent")
	fd_CourseContent_index = md_CourseContent.Fields().ByName("index")
	fd_CourseContent_courseId = md_CourseContent.Fields().ByName("courseId")
	fd_CourseContent_institution = md_CourseContent.Fields().ByName("institution")
	fd_CourseContent_title = md_CourseContent.Fields().ByName("title")
	fd_CourseContent_code = md_CourseContent.Fields().ByName("code")
	fd_CourseContent_workloadHours = md_CourseContent.Fields().ByName("workloadHours")
	fd_CourseContent_credits = md_CourseContent.Fields().ByName("credits")
	fd_CourseContent_description = md_CourseContent.Fields().ByName("description")
	fd_CourseContent_objectives = md_CourseContent.Fields().ByName("objectives")
	fd_CourseContent_topicUnits = md_CourseContent.Fields().ByName("topicUnits")
	fd_CourseContent_methodologies = md_CourseContent.Fields().ByName("methodologies")
	fd_CourseContent_evaluationMethods = md_CourseContent.Fields().ByName("evaluationMethods")
	fd_CourseContent_bibliographyBasic = md_CourseContent.Fields().ByName("bibliographyBasic")
	fd_CourseContent_bibliographyComplementary = md_CourseContent.Fields().ByName("bibliographyComplementary")
	fd_CourseContent_keywords = md_CourseContent.Fields().ByName("keywords")
	fd_CourseContent_contentHash = md_CourseContent.Fields().ByName("contentHash")
}

var _ protoreflect.Message = (*fastReflection_CourseContent)(nil)

type fastReflection_CourseContent CourseContent

func (x *CourseContent) ProtoReflect() protoreflect.Message {
	return (*fastReflection_CourseContent)(x)
}

func (x *CourseContent) slowProtoReflect() protoreflect.Message {
	mi := &file_academictoken_curriculum_course_content_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_CourseContent_messageType fastReflection_CourseContent_messageType
var _ protoreflect.MessageType = fastReflection_CourseContent_messageType{}

type fastReflection_CourseContent_messageType struct{}

func (x fastReflection_CourseContent_messageType) Zero() protoreflect.Message {
	return (*fastReflection_CourseContent)(nil)
}
func (x fastReflection_CourseContent_messageType) New() protoreflect.Message {
	return new(fastReflection_CourseContent)
}
func (x fastReflection_CourseContent_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_CourseContent
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_CourseContent) Descriptor() protoreflect.MessageDescriptor {
	return md_CourseContent
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_CourseContent) Type() protoreflect.MessageType {
	return _fastReflection_CourseContent_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_CourseContent) New() protoreflect.Message {
	return new(fastReflection_CourseContent)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_CourseContent) Interface() protoreflect.ProtoMessage {
	return (*CourseContent)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_CourseContent) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_CourseContent_index, value) {
			return
		}
	}
	if x.CourseId != "" {
		value := protoreflect.ValueOfString(x.CourseId)
		if !f(fd_CourseContent_courseId, value) {
			return
		}
	}
	if x.Institution != "" {
		value := protoreflect.ValueOfString(x.Institution)
		if !f(fd_CourseContent_institution, value) {
			return
		}
	}
	if x.Title != "" {
		value := protoreflect.ValueOfString(x.Title)
		if !f(fd_CourseContent_title, value) {
			return
		}
	}
	if x.Code != "" {
		value := protoreflect.ValueOfString(x.Code)
		if !f(fd_CourseContent_code, value) {
			return
		}
	}
	if x.WorkloadHours != uint64(0) {
		value := protoreflect.ValueOfUint64(x.WorkloadHours)
		if !f(fd_CourseContent_workloadHours, value) {
			return
		}
	}
	if x.Credits != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Credits)
		if !f(fd_CourseContent_credits, value) {
			return
		}
	}
	if x.Description != "" {
		value := protoreflect.ValueOfString(x.Description)
		if !f(fd_CourseContent_description, value) {
			return
		}
	}
	if len(x.Objectives) != 0 {
		value := protoreflect.ValueOfList(&_CourseContent_9_list{list: &x.Objectives})
		if !f(fd_CourseContent_objectives, value) {
			return
		}
	}
	if len(x.TopicUnits) != 0 {
		value := protoreflect.ValueOfList(&_CourseContent_10_list{list: &x.TopicUnits})
		if !f(fd_CourseContent_topicUnits, value) {
			return
		}
	}
	if len(x.Methodologies) != 0 {
		value := protoreflect.ValueOfList(&_CourseContent_11_list{list: &x.Methodologies})
		if !f(fd_CourseContent_methodologies, value) {
			return
		}
	}
	if len(x.EvaluationMethods) != 0 {
		value := protoreflect.ValueOfList(&_CourseContent_12_list{list: &x.EvaluationMethods})
		if !f(fd_CourseContent_evaluationMethods, value) {
			return
		}
	}
	if len(x.BibliographyBasic) != 0 {
		value := protoreflect.ValueOfList(&_CourseContent_13_list{list: &x.BibliographyBasic})
		if !f(fd_CourseContent_bibliographyBasic, value) {
			return
		}
	}
	if len(x.BibliographyComplementary) != 0 {
		value := protoreflect.ValueOfList(&_CourseContent_14_list{list: &x.BibliographyComplementary})
		if !f(fd_CourseContent_bibliographyComplementary, value) {
			return
		}
	}
	if len(x.Keywords) != 0 {
		value := protoreflect.ValueOfList(&_CourseContent_15_list{list: &x.Keywords})
		if !f(fd_CourseContent_keywords, value) {
			return
		}
	}
	if x.ContentHash != "" {
		value := protoreflect.ValueOfString(x.ContentHash)
		if !f(fd_CourseContent_contentHash, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_CourseContent) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "academictoken.curriculum.CourseContent.index":
		return x.Index != ""
	case "academictoken.curriculum.CourseContent.courseId":
		return x.CourseId != ""
	case "academictoken.curriculum.CourseContent.institution":
		return x.Institution != ""
	case "academictoken.curriculum.CourseContent.title":
		return x.Title != ""
	case "academictoken.curriculum.CourseContent.code":
		return x.Code != ""
	case "academictoken.curriculum.CourseContent.workloadHours":
		return x.WorkloadHours != uint64(0)
	case "academictoken.curriculum.CourseContent.credits":
		return x.Credits != uint64(0)
	case "academictoken.curriculum.CourseContent.description":
		return x.Description != ""
	case "academictoken.curriculum.CourseContent.objectives":
		return len(x.Objectives) != 0
	case "academictoken.curriculum.CourseContent.topicUnits":
		return len(x.TopicUnits) != 0
	case "academictoken.curriculum.CourseContent.methodologies":
		return len(x.Methodologies) != 0
	case "academictoken.curriculum.CourseContent.evaluationMethods":
		return len(x.EvaluationMethods) != 0
	case "academictoken.curriculum.CourseContent.bibliographyBasic":
		return len(x.BibliographyBasic) != 0
	case "academictoken.curriculum.CourseContent.bibliographyComplementary":
		return len(x.BibliographyComplementary) != 0
	case "academictoken.curriculum.CourseContent.keywords":
		return len(x.Keywords) != 0
	case "academictoken.curriculum.CourseContent.contentHash":
		return x.ContentHash != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.curriculum.CourseContent"))
		}
		panic(fmt.Errorf("message academictoken.curriculum.CourseContent does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CourseContent) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "academictoken.curriculum.CourseContent.index":
		x.Index = ""
	case "academictoken.curriculum.CourseContent.courseId":
		x.CourseId = ""
	case "academictoken.curriculum.CourseContent.institution":
		x.Institution = ""
	case "academictoken.curriculum.CourseContent.title":
		x.Title = ""
	case "academictoken.curriculum.CourseContent.code":
		x.Code = ""
	case "academictoken.curriculum.CourseContent.workloadHours":
		x.WorkloadHours = uint64(0)
	case "academictoken.curriculum.CourseContent.credits":
		x.Credits = uint64(0)
	case "academictoken.curriculum.CourseContent.description":
		x.Description = ""
	case "academictoken.curriculum.CourseContent.objectives":
		x.Objectives = nil
	case "academictoken.curriculum.CourseContent.topicUnits":
		x.TopicUnits = nil
	case "academictoken.curriculum.CourseContent.methodologies":
		x.Methodologies = nil
	case "academictoken.curriculum.CourseContent.evaluationMethods":
		x.EvaluationMethods = nil
	case "academictoken.curriculum.CourseContent.bibliographyBasic":
		x.BibliographyBasic = nil
	case "academictoken.curriculum.CourseContent.bibliographyComplementary":
		x.BibliographyComplementary = nil
	case "academictoken.curriculum.CourseContent.keywords":
		x.Keywords = nil
	case "academictoken.curriculum.CourseContent.contentHash":
		x.ContentHash = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.curriculum.CourseContent"))
		}
		panic(fmt.Errorf("message academictoken.curriculum.CourseContent does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_CourseContent) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "academictoken.curriculum.CourseContent.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "academictoken.curriculum.CourseContent.courseId":
		value := x.CourseId
		return protoreflect.ValueOfString(value)
	case "academictoken.curriculum.CourseContent.institution":
		value := x.Institution
		return protoreflect.ValueOfString(value)
	case "academictoken.curriculum.CourseContent.title":
		value := x.Title
		return protoreflect.ValueOfString(value)
	case "academictoken.curriculum.CourseContent.code":
		value := x.Code
		return protoreflect.ValueOfString(value)
	case "academictoken.curriculum.CourseContent.workloadHours":
		value := x.WorkloadHours
		return protoreflect.ValueOfUint64(value)
	case "academictoken.curriculum.CourseContent.credits":
		value := x.Credits
		return protoreflect.ValueOfUint64(value)
	case "academictoken.curriculum.CourseContent.description":
		value := x.Description
		return protoreflect.ValueOfString(value)
	case "academictoken.curriculum.CourseContent.objectives":
		if len(x.Objectives) == 0 {
			return protoreflect.ValueOfList(&_CourseContent_9_list{})
		}
		listValue := &_CourseContent_9_list{list: &x.Objectives}
		return protoreflect.ValueOfList(listValue)
	case "academictoken.curriculum.CourseContent.topicUnits":
		if len(x.TopicUnits) == 0 {
			return protoreflect.ValueOfList(&_CourseContent_10_list{})
		}
		listValue := &_CourseContent_10_list{list: &x.TopicUnits}
		return protoreflect.ValueOfList(listValue)
	case "academictoken.curriculum.CourseContent.methodologies":
		if len(x.Methodologies) == 0 {
			return protoreflect.ValueOfList(&_CourseContent_11_list{})
		}
		listValue := &_CourseContent_11_list{list: &x.Methodologies}
		return protoreflect.ValueOfList(listValue)
	case "academictoken.curriculum.CourseContent.evaluationMethods":
		if len(x.EvaluationMethods) == 0 {
			return protoreflect.ValueOfList(&_CourseContent_12_list{})
		}
		listValue := &_CourseContent_12_list{list: &x.EvaluationMethods}
		return protoreflect.ValueOfList(listValue)
	case "academictoken.curriculum.CourseContent.bibliographyBasic":
		if len(x.BibliographyBasic) == 0 {
			return protoreflect.ValueOfList(&_CourseContent_13_list{})
		}
		listValue := &_CourseContent_13_list{list: &x.BibliographyBasic}
		return protoreflect.ValueOfList(listValue)
	case "academictoken.curriculum.CourseContent.bibliographyComplementary":
		if len(x.BibliographyComplementary) == 0 {
			return protoreflect.ValueOfList(&_CourseContent_14_list{})
		}
		listValue := &_CourseContent_14_list{list: &x.BibliographyComplementary}
		return protoreflect.ValueOfList(listValue)
	case "academictoken.curriculum.CourseContent.keywords":
		if len(x.Keywords) == 0 {
			return protoreflect.ValueOfList(&_CourseContent_15_list{})
		}
		listValue := &_CourseContent_15_list{list: &x.Keywords}
		return protoreflect.ValueOfList(listValue)
	case "academictoken.curriculum.CourseContent.contentHash":
		value := x.ContentHash
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.curriculum.CourseContent"))
		}
		panic(fmt.Errorf("message academictoken.curriculum.CourseContent does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CourseContent) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "academictoken.curriculum.CourseContent.index":
		x.Index = value.Interface().(string)
	case "academictoken.curriculum.CourseContent.courseId":
		x.CourseId = value.Interface().(string)
	case "academictoken.curriculum.CourseContent.institution":
		x.Institution = value.Interface().(string)
	case "academictoken.curriculum.CourseContent.title":
		x.Title = value.Interface().(string)
	case "academictoken.curriculum.CourseContent.code":
		x.Code = value.Interface().(string)
	case "academictoken.curriculum.CourseContent.workloadHours":
		x.WorkloadHours = value.Uint()
	case "academictoken.curriculum.CourseContent.credits":
		x.Credits = value.Uint()
	case "academictoken.curriculum.CourseContent.description":
		x.Description = value.Interface().(string)
	case "academictoken.curriculum.CourseContent.objectives":
		lv := value.List()
		clv := lv.(*_CourseContent_9_list)
		x.Objectives = *clv.list
	case "academictoken.curriculum.CourseContent.topicUnits":
		lv := value.List()
		clv := lv.(*_CourseContent_10_list)
		x.TopicUnits = *clv.list
	case "academictoken.curriculum.CourseContent.methodologies":
		lv := value.List()
		clv := lv.(*_CourseContent_11_list)
		x.Methodologies = *clv.list
	case "academictoken.curriculum.CourseContent.evaluationMethods":
		lv := value.List()
		clv := lv.(*_CourseContent_12_list)
		x.EvaluationMethods = *clv.list
	case "academictoken.curriculum.CourseContent.bibliographyBasic":
		lv := value.List()
		clv := lv.(*_CourseContent_13_list)
		x.BibliographyBasic = *clv.list
	case "academictoken.curriculum.CourseContent.bibliographyComplementary":
		lv := value.List()
		clv := lv.(*_CourseContent_14_list)
		x.BibliographyComplementary = *clv.list
	case "academictoken.curriculum.CourseContent.keywords":
		lv := value.List()
		clv := lv.(*_CourseContent_15_list)
		x.Keywords = *clv.list
	case "academictoken.curriculum.CourseContent.contentHash":
		x.ContentHash = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.curriculum.CourseContent"))
		}
		panic(fmt.Errorf("message academictoken.curriculum.CourseContent does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CourseContent) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "academictoken.curriculum.CourseContent.objectives":
		if x.Objectives == nil {
			x.Objectives = []string{}
		}
		value := &_CourseContent_9_list{list: &x.Objectives}
		return protoreflect.ValueOfList(value)
	case "academictoken.curriculum.CourseContent.topicUnits":
		if x.TopicUnits == nil {
			x.TopicUnits = []string{}
		}
		value := &_CourseContent_10_list{list: &x.TopicUnits}
		return protoreflect.ValueOfList(value)
	case "academictoken.curriculum.CourseContent.methodologies":
		if x.Methodologies == nil {
			x.Methodologies = []string{}
		}
		value := &_CourseContent_11_list{list: &x.Methodologies}
		return protoreflect.ValueOfList(value)
	case "academictoken.curriculum.CourseContent.evaluationMethods":
		if x.EvaluationMethods == nil {
			x.EvaluationMethods = []string{}
		}
		value := &_CourseContent_12_list{list: &x.EvaluationMethods}
		return protoreflect.ValueOfList(value)
	case "academictoken.curriculum.CourseContent.bibliographyBasic":
		if x.BibliographyBasic == nil {
			x.BibliographyBasic = []string{}
		}
		value := &_CourseContent_13_list{list: &x.BibliographyBasic}
		return protoreflect.ValueOfList(value)
	case "academictoken.curriculum.CourseContent.bibliographyComplementary":
		if x.BibliographyComplementary == nil {
			x.BibliographyComplementary = []string{}
		}
		value := &_CourseContent_14_list{list: &x.BibliographyComplementary}
		return protoreflect.ValueOfList(value)
	case "academictoken.curriculum.CourseContent.keywords":
		if x.Keywords == nil {
			x.Keywords = []string{}
		}
		value := &_CourseContent_15_list{list: &x.Keywords}
		return protoreflect.ValueOfList(value)
	case "academictoken.curriculum.CourseContent.index":
		panic(fmt.Errorf("field index of message academictoken.curriculum.CourseContent is not mutable"))
	case "academictoken.curriculum.CourseContent.courseId":
		panic(fmt.Errorf("field courseId of message academictoken.curriculum.CourseContent is not mutable"))
	case "academictoken.curriculum.CourseContent.institution":
		panic(fmt.Errorf("field institution of message academictoken.curriculum.CourseContent is not mutable"))
	case "academictoken.curriculum.CourseContent.title":
		panic(fmt.Errorf("field title of message academictoken.curriculum.CourseContent is not mutable"))
	case "academictoken.curriculum.CourseContent.code":
		panic(fmt.Errorf("field code of message academictoken.curriculum.CourseContent is not mutable"))
	case "academictoken.curriculum.CourseContent.workloadHours":
		panic(fmt.Errorf("field workloadHours of message academictoken.curriculum.CourseContent is not mutable"))
	case "academictoken.curriculum.CourseContent.credits":
		panic(fmt.Errorf("field credits of message academictoken.curriculum.CourseContent is not mutable"))
	case "academictoken.curriculum.CourseContent.description":
		panic(fmt.Errorf("field description of message academictoken.curriculum.CourseContent is not mutable"))
	case "academictoken.curriculum.CourseContent.contentHash":
		panic(fmt.Errorf("field contentHash of message academictoken.curriculum.CourseContent is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.curriculum.CourseContent"))
		}
		panic(fmt.Errorf("message academictoken.curriculum.CourseContent does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_CourseContent) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "academictoken.curriculum.CourseContent.index":
		return protoreflect.ValueOfString("")
	case "academictoken.curriculum.CourseContent.courseId":
		return protoreflect.ValueOfString("")
	case "academictoken.curriculum.CourseContent.institution":
		return protoreflect.ValueOfString("")
	case "academictoken.curriculum.CourseContent.title":
		return protoreflect.ValueOfString("")
	case "academictoken.curriculum.CourseContent.code":
		return protoreflect.ValueOfString("")
	case "academictoken.curriculum.CourseContent.workloadHours":
		return protoreflect.ValueOfUint64(uint64(0))
	case "academictoken.curriculum.CourseContent.credits":
		return protoreflect.ValueOfUint64(uint64(0))
	case "academictoken.curriculum.CourseContent.description":
		return protoreflect.ValueOfString("")
	case "academictoken.curriculum.CourseContent.objectives":
		list := []string{}
		return protoreflect.ValueOfList(&_CourseContent_9_list{list: &list})
	case "academictoken.curriculum.CourseContent.topicUnits":
		list := []string{}
		return protoreflect.ValueOfList(&_CourseContent_10_list{list: &list})
	case "academictoken.curriculum.CourseContent.methodologies":
		list := []string{}
		return protoreflect.ValueOfList(&_CourseContent_11_list{list: &list})
	case "academictoken.curriculum.CourseContent.evaluationMethods":
		list := []string{}
		return protoreflect.ValueOfList(&_CourseContent_12_list{list: &list})
	case "academictoken.curriculum.CourseContent.bibliographyBasic":
		list := []string{}
		return protoreflect.ValueOfList(&_CourseContent_13_list{list: &list})
	case "academictoken.curriculum.CourseContent.bibliographyComplementary":
		list := []string{}
		return protoreflect.ValueOfList(&_CourseContent_14_list{list: &list})
	case "academictoken.curriculum.CourseContent.keywords":
		list := []string{}
		return protoreflect.ValueOfList(&_CourseContent_15_list{list: &list})
	case "academictoken.curriculum.CourseContent.contentHash":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.curriculum.CourseContent"))
		}
		panic(fmt.Errorf("message academictoken.curriculum.CourseContent does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_CourseContent) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in academictoken.curriculum.CourseContent", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_CourseContent) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CourseContent) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_CourseContent) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_CourseContent) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*CourseContent)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.CourseId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Institution)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Title)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Code)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.WorkloadHours != 0 {
			n += 1 + runtime.Sov(uint64(x.WorkloadHours))
		}
		if x.Credits != 0 {
			n += 1 + runtime.Sov(uint64(x.Credits))
		}
		l = len(x.Description)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.Objectives) > 0 {
			for _, s := range x.Objectives {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.TopicUnits) > 0 {
			for _, s := range x.TopicUnits {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.Methodologies) > 0 {
			for _, s := range x.Methodologies {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.EvaluationMethods) > 0 {
			for _, s := range x.EvaluationMethods {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.BibliographyBasic) > 0 {
			for _, s := range x.BibliographyBasic {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.BibliographyComplementary) > 0 {
			for _, s := range x.BibliographyComplementary {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.Keywords) > 0 {
			for _, s := range x.Keywords {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		l = len(x.ContentHash)
		if l > 0 {
			n += 2 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*CourseContent)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.ContentHash) > 0 {
			i -= len(x.ContentHash)
			copy(dAtA[i:], x.ContentHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ContentHash)))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
		if len(x.Keywords) > 0 {
			for iNdEx := len(x.Keywords) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Keywords[iNdEx])
				copy(dAtA[i:], x.Keywords[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Keywords[iNdEx])))
				i--
				dAtA[i] = 0x7a
			}
		}
		if len(x.BibliographyComplementary) > 0 {
			for iNdEx := len(x.BibliographyComplementary) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.BibliographyComplementary[iNdEx])
				copy(dAtA[i:], x.BibliographyComplementary[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.BibliographyComplementary[iNdEx])))
				i--
				dAtA[i] = 0x72
			}
		}
		if len(x.BibliographyBasic) > 0 {
			for iNdEx := len(x.BibliographyBasic) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.BibliographyBasic[iNdEx])
				copy(dAtA[i:], x.BibliographyBasic[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.BibliographyBasic[iNdEx])))
				i--
				dAtA[i] = 0x6a
			}
		}
		if len(x.EvaluationMethods) > 0 {
			for iNdEx := len(x.EvaluationMethods) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.EvaluationMethods[iNdEx])
				copy(dAtA[i:], x.EvaluationMethods[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.EvaluationMethods[iNdEx])))
				i--
				dAtA[i] = 0x62
			}
		}
		if len(x.Methodologies) > 0 {
			for iNdEx := len(x.Methodologies) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Methodologies[iNdEx])
				copy(dAtA[i:], x.Methodologies[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Methodologies[iNdEx])))
				i--
				dAtA[i] = 0x5a
			}
		}
		if len(x.TopicUnits) > 0 {
			for iNdEx := len(x.TopicUnits) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.TopicUnits[iNdEx])
				copy(dAtA[i:], x.TopicUnits[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TopicUnits[iNdEx])))
				i--
				dAtA[i] = 0x52
			}
		}
		if len(x.Objectives) > 0 {
			for iNdEx := len(x.Objectives) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Objectives[iNdEx])
				copy(dAtA[i:], x.Objectives[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Objectives[iNdEx])))
				i--
				dAtA[i] = 0x4a
			}
		}
		if len(x.Description) > 0 {
			i -= len(x.Description)
			copy(dAtA[i:], x.Description)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Description)))
			i--
			dAtA[i] = 0x42
		}
		if x.Credits != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Credits))
			i--
			dAtA[i] = 0x38
		}
		if x.WorkloadHours != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.WorkloadHours))
			i--
			dAtA[i] = 0x30
		}
		if len(x.Code) > 0 {
			i -= len(x.Code)
			copy(dAtA[i:], x.Code)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Code)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Title) > 0 {
			i -= len(x.Title)
			copy(dAtA[i:], x.Title)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Title)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Institution) > 0 {
			i -= len(x.Institution)
			copy(dAtA[i:], x.Institution)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Institution)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.CourseId) > 0 {
			i -= len(x.CourseId)
			copy(dAtA[i:], x.CourseId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.CourseId)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*CourseContent)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: CourseContent: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: CourseContent: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CourseId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.CourseId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Institution", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Institution = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Title = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Code = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field WorkloadHours", wireType)
				}
				x.WorkloadHours = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.WorkloadHours |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Credits", wireType)
				}
				x.Credits = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Credits |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Description = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Objectives", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Objectives = append(x.Objectives, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TopicUnits", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TopicUnits = append(x.TopicUnits, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 11:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Methodologies", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Methodologies = append(x.Methodologies, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 12:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EvaluationMethods", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.EvaluationMethods = append(x.EvaluationMethods, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 13:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BibliographyBasic", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.BibliographyBasic = append(x.BibliographyBasic, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 14:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BibliographyComplementary", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.BibliographyComplementary = append(x.BibliographyComplementary, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 15:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Keywords", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Keywords = append(x.Keywords, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 16:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ContentHash", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ContentHash = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: academictoken/curriculum/course_content.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index                     string   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	CourseId                  string   `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	Institution               string   `protobuf:"bytes,3,opt,name=institution,proto3" json:"institution,omitempty"`
	Title                     string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Code                      string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	WorkloadHours             uint64   `protobuf:"varint,6,opt,name=workloadHours,proto3" json:"workloadHours,omitempty"`
	Credits                   uint64   `protobuf:"varint,7,opt,name=credits,proto3" json:"credits,omitempty"`
	Description               string   `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Objectives                []string `protobuf:"bytes,9,rep,name=objectives,proto3" json:"objectives,omitempty"`
	TopicUnits                []string `protobuf:"bytes,10,rep,name=topicUnits,proto3" json:"topicUnits,omitempty"`
	Methodologies             []string `protobuf:"bytes,11,rep,name=methodologies,proto3" json:"methodologies,omitempty"`
	EvaluationMethods         []string `protobuf:"bytes,12,rep,name=evaluationMethods,proto3" json:"evaluationMethods,omitempty"`
	BibliographyBasic         []string `protobuf:"bytes,13,rep,name=bibliographyBasic,proto3" json:"bibliographyBasic,omitempty"`
	BibliographyComplementary []string `protobuf:"bytes,14,rep,name=bibliographyComplementary,proto3" json:"bibliographyComplementary,omitempty"`
	Keywords                  []string `protobuf:"bytes,15,rep,name=keywords,proto3" json:"keywords,omitempty"`
	ContentHash               string   `protobuf:"bytes,16,opt,name=contentHash,proto3" json:"contentHash,omitempty"`
}

func (x *CourseContent) Reset() {
	*x = CourseContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_academictoken_curriculum_course_content_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseContent) ProtoMessage() {}

// Deprecated: Use CourseContent.ProtoReflect.Descriptor instead.
func (*CourseContent) Descriptor() ([]byte, []int) {
	return file_academictoken_curriculum_course_content_proto_rawDescGZIP(), []int{0}
}

func (x *CourseContent) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *CourseContent) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseContent) GetInstitution() string {
	if x != nil {
		return x.Institution
	}
	return ""
}

func (x *CourseContent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseContent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CourseContent) GetWorkloadHours() uint64 {
	if x != nil {
		return x.WorkloadHours
	}
	return 0
}

func (x *CourseContent) GetCredits() uint64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *CourseContent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CourseContent) GetObjectives() []string {
	if x != nil {
		return x.Objectives
	}
	return nil
}

func (x *CourseContent) GetTopicUnits() []string {
	if x != nil {
		return x.TopicUnits
	}
	return nil
}

func (x *CourseContent) GetMethodologies() []string {
	if x != nil {
		return x.Methodologies
	}
	return nil
}

func (x *CourseContent) GetEvaluationMethods() []string {
	if x != nil {
		return x.EvaluationMethods
	}
	return nil
}

func (x *CourseContent) GetBibliographyBasic() []string {
	if x != nil {
		return x.BibliographyBasic
	}
	return nil
}

func (x *CourseContent) GetBibliographyComplementary() []string {
	if x != nil {
		return x.BibliographyComplementary
	}
	return nil
}

func (x *CourseContent) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *CourseContent) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

var File_academictoken_curriculum_course_content_proto protoreflect.FileDescriptor

var file_academictoken_curriculum_course_content_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f,
	0x63, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x75, 0x6d, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x18, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x63,
	0x75, 0x72, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x75, 0x6d, 0x22, 0xad, 0x04, 0x0a, 0x0d, 0x43, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x69, 0x6e, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x77, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x65,
	0x73, 0x12, 0x2c, 0x0a, 0x11, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x65, 0x76,
	0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12,
	0x2c, 0x0a, 0x11, 0x62, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x79, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x62, 0x69, 0x62, 0x6c,
	0x69, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x79, 0x42, 0x61, 0x73, 0x69, 0x63, 0x12, 0x3c, 0x0a,
	0x19, 0x62, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x79, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x79, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x19, 0x62, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x79, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x42, 0xf7, 0x01, 0x0a, 0x1c, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e,
	0x63, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x75, 0x6d, 0x42, 0x12, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x69, 0x61,
	0x6e, 0x63, 0x61, 0x2d, 0x32, 0x39, 0x4d, 0x53, 0x50, 0x2f, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d,
	0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x63, 0x61, 0x64,
	0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x69, 0x63,
	0x75, 0x6c, 0x75, 0x6d, 0xa2, 0x02, 0x03, 0x41, 0x43, 0x58, 0xaa, 0x02, 0x18, 0x41, 0x63, 0x61,
	0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x69,
	0x63, 0x75, 0x6c, 0x75, 0x6d, 0xca, 0x02, 0x18, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5c, 0x43, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x75, 0x6d,
	0xe2, 0x02, 0x24, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5c, 0x43, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x75, 0x6d, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x19, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d,
	0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3a, 0x3a, 0x43, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75,
	0x6c, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_academictoken_curriculum_course_content_proto_rawDescOnce sync.Once
	file_academictoken_curriculum_course_content_proto_rawDescData = file_academictoken_curriculum_course_content_proto_rawDesc
)

func file_academictoken_curriculum_course_content_proto_rawDescGZIP() []byte {
	file_academictoken_curriculum_course_content_proto_rawDescOnce.Do(func() {
		file_academictoken_curriculum_course_content_proto_rawDescData = protoimpl.X.CompressGZIP(file_academictoken_curriculum_course_content_proto_rawDescData)
	})
	return file_academictoken_curriculum_course_content_proto_rawDescData
}

var file_academictoken_curriculum_course_content_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_academictoken_curriculum_course_content_proto_goTypes = []interface{}{
	(*CourseContent)(nil), // 0: academictoken.curriculum.CourseContent
}
var file_academictoken_curriculum_course_content_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_academictoken_curriculum_course_content_proto_init() }
func file_academictoken_curriculum_course_content_proto_init() {
	if File_academictoken_curriculum_course_content_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_academictoken_curriculum_course_content_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_academictoken_curriculum_course_content_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_academictoken_curriculum_course_content_proto_goTypes,
		DependencyIndexes: file_academictoken_curriculum_course_content_proto_depIdxs,
		MessageInfos:      file_academictoken_curriculum_course_content_proto_msgTypes,
	}.Build()
	File_academictoken_curriculum_course_content_proto = out.File
	file_academictoken_curriculum_course_content_proto_rawDesc = nil
	file_academictoken_curriculum_course_content_proto_goTypes = nil
	file_academictoken_curriculum_course_content_proto_depIdxs = nil
}
