// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: academictoken/academicnft/tx.proto

package academicnft

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName       = "/academictoken.academicnft.Msg/UpdateParams"
	Msg_MintCourseNft_FullMethodName      = "/academictoken.academicnft.Msg/MintCourseNft"
	Msg_TransferCourseNft_FullMethodName  = "/academictoken.academicnft.Msg/TransferCourseNft"
	Msg_ApproveEquivalence_FullMethodName = "/academictoken.academicnft.Msg/ApproveEquivalence"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	MintCourseNft(ctx context.Context, in *MsgMintCourseNft, opts ...grpc.CallOption) (*MsgMintCourseNftResponse, error)
	TransferCourseNft(ctx context.Context, in *MsgTransferCourseNft, opts ...grpc.CallOption) (*MsgTransferCourseNftResponse, error)
	ApproveEquivalence(ctx context.Context, in *MsgApproveEquivalence, opts ...grpc.CallOption) (*MsgApproveEquivalenceResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MintCourseNft(ctx context.Context, in *MsgMintCourseNft, opts ...grpc.CallOption) (*MsgMintCourseNftResponse, error) {
	out := new(MsgMintCourseNftResponse)
	err := c.cc.Invoke(ctx, Msg_MintCourseNft_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferCourseNft(ctx context.Context, in *MsgTransferCourseNft, opts ...grpc.CallOption) (*MsgTransferCourseNftResponse, error) {
	out := new(MsgTransferCourseNftResponse)
	err := c.cc.Invoke(ctx, Msg_TransferCourseNft_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ApproveEquivalence(ctx context.Context, in *MsgApproveEquivalence, opts ...grpc.CallOption) (*MsgApproveEquivalenceResponse, error) {
	out := new(MsgApproveEquivalenceResponse)
	err := c.cc.Invoke(ctx, Msg_ApproveEquivalence_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	MintCourseNft(context.Context, *MsgMintCourseNft) (*MsgMintCourseNftResponse, error)
	TransferCourseNft(context.Context, *MsgTransferCourseNft) (*MsgTransferCourseNftResponse, error)
	ApproveEquivalence(context.Context, *MsgApproveEquivalence) (*MsgApproveEquivalenceResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) MintCourseNft(context.Context, *MsgMintCourseNft) (*MsgMintCourseNftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintCourseNft not implemented")
}
func (UnimplementedMsgServer) TransferCourseNft(context.Context, *MsgTransferCourseNft) (*MsgTransferCourseNftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferCourseNft not implemented")
}
func (UnimplementedMsgServer) ApproveEquivalence(context.Context, *MsgApproveEquivalence) (*MsgApproveEquivalenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveEquivalence not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MintCourseNft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMintCourseNft)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MintCourseNft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_MintCourseNft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MintCourseNft(ctx, req.(*MsgMintCourseNft))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferCourseNft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferCourseNft)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferCourseNft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_TransferCourseNft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferCourseNft(ctx, req.(*MsgTransferCourseNft))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ApproveEquivalence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgApproveEquivalence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ApproveEquivalence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ApproveEquivalence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ApproveEquivalence(ctx, req.(*MsgApproveEquivalence))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academictoken.academicnft.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "MintCourseNft",
			Handler:    _Msg_MintCourseNft_Handler,
		},
		{
			MethodName: "TransferCourseNft",
			Handler:    _Msg_TransferCourseNft_Handler,
		},
		{
			MethodName: "ApproveEquivalence",
			Handler:    _Msg_ApproveEquivalence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "academictoken/academicnft/tx.proto",
}
